### PR TITLE
Fix placement for non-primitive shapes coming from freecad

### LINKED ISSUE #651: Rotation transforms not working with the Gear example
The object appears to render, but appears in the original position after releasing the mouse.

### PR DESCRIPTION
**Pull request by arjxn-py**
Shall fix #651

### CODE REVIEW

File: packages/occ-worker/src/occapi/any.ts [hunk 1]
```diff
@@ -9,7 +9,11 @@ export function _Any(
...
   const { Content, Type, Placement } = arg;
-  const result = _loadObjectFile({ content: Content, type: Type });
+  const result = _loadObjectFile({
+    content: Content,
+    type: Type,
+    placement: Placement
+  });
   if (result) {
     return setShapePlacement(result, Placement);
   }
```
Comment (martinRenou) [inline packages/occ-worker/src/occapi/any.ts:19]: We don't need this anymore since `_loadObjectFile` is already setting the placement correctly now

File: packages/occ-worker/src/occapi/index.ts [hunk 2]
```diff
@@ -66,6 +66,11 @@ export const Fillet = operatorCache<IFillet>('Part::Fillet', _Fillet);
 export const ObjectFile = operatorCache<{
   content: string;
   type: IAny['Type'];
+  placement: {
```
Comment (trungleduc) [inline packages/occ-worker/src/occapi/index.ts:69]:
```suggestion
  placement?: {
```

Comment (trungleduc) [reply packages/occ-worker/src/occapi/index.ts:69]: The generic type parameter here takes the same type of the first argument of `_loadObjectFile`

Comment (arjxn-py) [reply packages/occ-worker/src/occapi/index.ts]: > The generic type parameter here takes the same type of the first argument of `_loadObjectFile`

It is of same type as type in `_loadObjectFile`, do we want to change?

File: packages/occ-worker/src/occapi/any.ts (hunk 1 above)
Comment (arjxn-py) [reply packages/occ-worker/src/occapi/any.ts]: Done, Thanks :)

**Review by martinRenou — APPROVED** [review]
Thanks!

**Review by trungleduc — APPROVED** [review]

**Comment by martinRenou** [comment]
https://github.com/user-attachments/assets/e5409344-11c9-44e2-b7c9-4e5414430cec

Confirming it works in the JupyterLite deployment!
