### PR TITLE
Fix bounding box on exploded view

### LINKED ISSUE #491: The bounding box does seems to exagerate the exploded view factor
Image

### PR DESCRIPTION
**Pull request by arjxn-py**
https://github.com/user-attachments/assets/ff24266d-9493-4911-b8cc-90c80fcd68dd

Shall fix #491

### CODE REVIEW

File: packages/base/src/3dview/mainview.tsx [hunk 1]
```diff
@@ -1064,6 +1071,7 @@ export class MainView extends React.Component<IProps, IStates> {
         boundingBox.position.copy(center);
 
         selectedMesh.add(boundingBox);
```
Comment (martinRenou) [inline packages/base/src/3dview/mainview.tsx:1073]: Shall we not do this anymore? Now that you add it to the group I feel like we should not also add it to the mesh?

Comment (arjxn-py) [reply packages/base/src/3dview/mainview.tsx:1073]: Yes, that sounds good.

File: packages/base/src/3dview/mainview.tsx [hunk 2]
```diff
@@ -1000,6 +1000,13 @@ export class MainView extends React.Component<IProps, IStates> {
         selectedMesh.remove(boundingBox);
       }
```
Comment (martinRenou) [inline packages/base/src/3dview/mainview.tsx:1001]: I believe we also don't need to remove `boundingBox` from `selectedMesh` too, now that you don't add it to the mesh anymore :)

**Review by martinRenou — COMMENTED** [review]
Working great!!!

File: packages/base/src/3dview/mainview.tsx (hunk 2 above)
Comment (arjxn-py) [reply packages/base/src/3dview/mainview.tsx]: Oops! I should've thought that 😅

File: packages/base/src/3dview/mainview.tsx [hunk 3]
```diff
@@ -996,8 +996,12 @@ export class MainView extends React.Component<IProps, IStates> {
...
 
       const boundingBox = selectedMesh.getObjectByName(SELECTION_BOUNDING_BOX);
```
Comment (martinRenou) [inline packages/base/src/3dview/mainview.tsx:998]: Last comment 😁 this will eventually never return anything now that you're not adding the box to the mesh, let's do only

```typescript
      const groupBoundingBox = this._meshGroup?.getObjectByName(
        SELECTION_BOUNDING_BOX
      );
```

Comment (arjxn-py) [reply packages/base/src/3dview/mainview.tsx:998]: Thanks for making it better 🚀

**Review by martinRenou — APPROVED** [review]
🚀
